version: '3'

services:
  e2e:
    image: cypress
    build:
      context: .
      dockerfile: ./dockerfiles/cypress.dockerfile
    depends_on:
      - nginx
    volumes: 
      - ./results:/app/results
    environment:
      - CYPRESS_baseUrl=http://nginx
    command: npm run test:ci

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    ports:
      - 8080:80